name = "ak-media"
main = "index.js"
compatibility_date = "2025-02-14"
keep_vars = true

vars = { AEM_HOSTNAME = "main--ak-media--author-kit.aem.live" }

[env.dev]
vars = { ENVIRONMENT = "dev", AEM_HOSTNAME = "main--ak-media--author-kit.aem.page" }
